upstream tramites_backend {
    server tramites_1:3333 max_fails=1 fail_timeout=10s;
    server tramites_2:3333 max_fails=1 fail_timeout=10s;
}

server {
    listen 80;

    location /tramites {
        proxy_pass http://tramites_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_next_upstream error timeout http_502 http_503 http_504;
        proxy_next_upstream_tries 2;
    }
}
